# Configurations
title:            AI Universe Courses
longtitle:        AI Universe Courses
author:           Feras Kanaan Darwich
email:            ai@feras.me
description: >
  a curated gateway into the vast world of Artificial Intelligence. This project brings together free and open-access courses across the entire AI spectrum

version:          1.0
gitbook_version:  3.2.3

tracker:
  google_analytics: "G-6ZST125FZH"

url:              'https://ai.feras.me'  # Custom production domain
# Keep empty for root-level site both locally and in production
baseurl:          ''
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/
  llm:
    output: true
    permalink: /:collection/:path/
  agentic:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - llm
  - agentic
  - posts
  - pages
  - others

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji

# Search configuration for gitbook-style search_plus_index.json
# This enables inclusion of regular HTML pages and specified collections in the search index.
gitbook_search:
  include:
    pages: true            # include site.html_pages (like README-based home, about, etc.)
    collections:
      - llm
      - agentic
      - posts
      - pages
      - others
  exclude:
    files: []              # list relative paths you want excluded
    tags: []               # list tags to exclude
    categories: []         # list categories to exclude
